package capability

// The argument names, split out of usage_text.go when that file reached the
// 250-line ceiling AGENTS.md sets. This is the natural seam: a separate table
// answering a separate question, held by its own two tests in usage_test.go --
// every option that takes a value names it, and a name with no such option
// behind it is dead weight.

// valuePlaceholders name what an option's argument is, keyed by command and letter.
// Without these the synopsis would read `-k VALUE`, which says nothing.
var valuePlaceholders = map[string]string{
	"cpioF":       "FILE",
	"cpioH":       "FORMAT",
	"base64w":     "COLUMN",
	"sha3suma":    "BITS",
	"foldw":       "WIDTH",
	"stringsn":    "LENGTH",
	"stringst":    "RADIX",
	"expandt":     "WIDTH",
	"unexpandt":   "WIDTH",
	"joinj":       "FIELD",
	"join1":       "FIELD",
	"join2":       "FIELD",
	"joint":       "CHAR",
	"base32w":     "COLUMN",
	"shufn":       "COUNT",
	"shufi":       "LO-HI",
	"iconvf":      "ENCODING",
	"iconvt":      "ENCODING",
	"iconvo":      "FILE",
	"tarf":        "ARCHIVE",
	"tarC":        "DIR",
	"unzipd":      "DIR",
	"unzipx":      "PATTERN",
	"odA":         "RADIX",
	"odt":         "TYPE",
	"hexdumpA":    "RADIX",
	"hexdumpt":    "TYPE",
	"hdA":         "RADIX",
	"hdt":         "TYPE",
	"uudecodeo":   "FILE",
	"diffU":       "LINES",
	"diffL":       "LABEL",
	"patchp":      "COUNT",
	"patchi":      "DIFF",
	"wgetO":       "FILE",
	"wgeto":       "LOGFILE",
	"wgetP":       "DIR",
	"wgetU":       "AGENT",
	"wgetT":       "SECONDS",
	"wgetheader":  "NAME: VALUE",
	"ncp":         "PORT",
	"ncw":         "SECONDS",
	"whoish":      "SERVER",
	"whoisp":      "PORT",
	"ssl_clientn": "SNI",
	"ssl_clients": "HOST",
	"ssl_clienth": "HOST",
	"httpdp":      "PORT",
	"httpdh":      "DIR",
	"httpda":      "ADDRESS",
	"ftpgetu":     "USER",
	"ftpgetp":     "PASSWORD",
	"ftpgetP":     "PORT",
	"ftpputu":     "USER",
	"ftpputp":     "PASSWORD",
	"ftpputP":     "PORT",
	"topn":        "COUNT",
	"topd":        "SECONDS",
	"tops":        "COLUMN",
	"topo":        "COLUMNS",
	"topf":        "TEXT",
	"cutb":        "LIST",
	"cutc":        "LIST",
	"cutd":        "DELIM",
	"cutf":        "LIST",
	"dated":       "DATESTRING",
	"grepm":       "COUNT",
	"headn":       "LINES",
	"headc":       "BYTES",
	"mkdirm":      "MODE",
	"nlb":         "STYLE",
	"pasted":      "DELIMS",
	"sortk":       "KEYDEF",
	"sortt":       "SEP",
	"statc":       "FORMAT",
	"splitl":      "LINES",
	"suc":         "COMMAND",
	"sus":         "SHELL",
	"tailn":       "LINES",
	"tailc":       "BYTES",
	"xargsn":      "COUNT",
	"xargsI":      "REPLACE",
}
