package runtime

import (
	"fmt"
	"strings"
)

// parseFunctionDefinition reads all three spellings a function can be written in:
//
//	name() { body; }            POSIX
//	function name { body; }     ksh, and bash accepts it
//	function name() { body; }   both at once, which bash also accepts
//
// The `function` keyword was refused outright -- `unsupported syntax: function` -- and
// it is the spelling half the shell scripts in the world use, including every one
// generated by a tool that prefers the keyword for readability.
func parseFunctionDefinition(line string, budget *parseBudget, depth int) (functionDefinition, bool, error) {
	line = strings.TrimSpace(line)
	rest, hasKeyword := cutFunctionKeyword(line)
	if hasKeyword {
		line = rest
	}
	nameEnd := strings.IndexByte(line, '(')
	if nameEnd < 0 {
		if !hasKeyword {
			return functionDefinition{}, false, nil
		}
		// `function name { body; }`: no parentheses, so the name ends at the blank
		// before the body.
		return parseKeywordFunction(line, budget, depth)
	}
	rawName := strings.TrimSpace(line[:nameEnd])
	name, ok := newFunctionName(rawName)
	if !ok {
		return functionDefinition{}, false, nil
	}
	index := nameEnd + 1
	for index < len(line) && (line[index] == ' ' || line[index] == '\t') {
		index++
	}
	if index >= len(line) || line[index] != ')' {
		return functionDefinition{}, true, fmt.Errorf("%w: missing ) in function definition", ErrIncompleteScript)
	}
	remainder := strings.TrimSpace(line[index+1:])
	if remainder == "" {
		return functionDefinition{}, true, fmt.Errorf("%w: missing function body", ErrIncompleteScript)
	}
	body, err := parseFunctionBody(remainder, budget, depth)
	if err != nil {
		return functionDefinition{}, true, err
	}
	return functionDefinition{name: name, body: body}, true, nil
}

// functionHeaderBeforeCompound finds `name() if ...`, a function whose body is a keyword
// compound rather than a brace group: an if, a loop or a case, which POSIX 2.9.5 allows and
// both references take. It answers the name and the compound's header, for the span builder
// to parse the compound as it parses any, with the definition around it; see
// wrapCompoundAfterOperator.
func functionHeaderBeforeCompound(line string) (string, string, bool) {
	text, _ := cutFunctionKeyword(line)
	open := strings.IndexByte(text, '(')
	if open <= 0 {
		return "", "", false
	}
	name := strings.TrimSpace(text[:open])
	if _, ok := newFunctionName(name); !ok {
		return "", "", false
	}
	rest := strings.TrimLeft(text[open+1:], " \t")
	if !strings.HasPrefix(rest, ")") {
		return "", "", false
	}
	rest = strings.TrimLeft(rest[1:], " \t")
	if !beginsWithCompoundKeyword(rest) {
		return "", "", false
	}
	return name, rest, true
}

func standaloneFunctionHeader(line string) bool {
	rawName, remainder, found := strings.Cut(line, "(")
	if !found {
		return false
	}
	if _, ok := newFunctionName(strings.TrimSpace(rawName)); !ok {
		return false
	}
	return strings.TrimSpace(remainder) == ")"
}

// newFunctionName accepts the names both references accept, which is nearly any word:
// lib::fn, my-fn, a.b and 1fn are the names library code gives functions to fake
// namespaces, and each was a syntax error that stopped the whole script. Only a word
// that is something else is refused: one with blanks, quoting, an expansion, an operator,
// a bracket, a comment's `#`, or the `=` of an assignment. So is one ending in ?, *, +,
// @ or !, since here `@(` always begins an extended pattern.
func newFunctionName(value string) (functionName, bool) {
	if value == "" || strings.ContainsAny(value, " \t\n\"'\\$`()<>|&;={}[]#") {
		return functionName{}, false
	}
	if strings.IndexByte("?*+@!", value[len(value)-1]) >= 0 {
		return functionName{}, false
	}
	return functionName{value: value}, true
}

func parseFunctionBody(source string, budget *parseBudget, depth int) (commandNode, error) {
	// `f() [[ ... ]]` and `f() (( ... ))`: bash's conditional and arithmetic commands are
	// compound commands too, and are parsed as the brace group around them. The keyword
	// compounds never arrive here; see functionHeaderBeforeCompound.
	if strings.HasPrefix(source, "[[") || strings.HasPrefix(source, "((") {
		source = "{ " + source + "\n}"
	}
	masked, groups, err := extractGroupCommands(source, budget, depth+1)
	if err != nil {
		return nil, err
	}
	tokens, err := scanExtractedGroups(masked, groups, budget, depth+1)
	if err != nil {
		return nil, err
	}
	if len(tokens) > 0 && isAndOrOperator(tokens[len(tokens)-1].kind) {
		return nil, fmt.Errorf("%w: missing command after %s", ErrIncompleteScript, tokens[len(tokens)-1].value)
	}
	command, redirects, err := parseRedirectsWithBudget(tokens, budget)
	if err != nil {
		return nil, classifyCommandError(err)
	}
	if len(command) != 1 {
		return nil, fmt.Errorf("syntax error: function body must be a compound command")
	}
	group := command[0].group
	if group == nil {
		return nil, fmt.Errorf("syntax error: function body must be a compound command")
	}
	return group.withRedirects(redirects), nil
}

// cutFunctionKeyword strips a leading `function` keyword, reporting whether there was
// one. A blank must follow it, or `functional() { ...; }` would lose its name.
func cutFunctionKeyword(line string) (string, bool) {
	rest, ok := strings.CutPrefix(line, "function")
	if !ok || rest == "" {
		return line, false
	}
	if rest[0] != ' ' && rest[0] != '	' {
		return line, false
	}
	return strings.TrimLeft(rest, " 	"), true
}

// parseKeywordFunction reads `name { body; }`, the keyword form without parentheses.
func parseKeywordFunction(line string, budget *parseBudget, depth int) (functionDefinition, bool, error) {
	cut := strings.IndexAny(line, " 	{")
	if cut <= 0 {
		return functionDefinition{}, true, fmt.Errorf("%w: missing function body", ErrIncompleteScript)
	}
	name, ok := newFunctionName(strings.TrimSpace(line[:cut]))
	if !ok {
		return functionDefinition{}, false, nil
	}
	remainder := strings.TrimSpace(line[cut:])
	if remainder == "" {
		return functionDefinition{}, true, fmt.Errorf("%w: missing function body", ErrIncompleteScript)
	}
	body, err := parseFunctionBody(remainder, budget, depth)
	if err != nil {
		return functionDefinition{}, true, err
	}
	return functionDefinition{name: name, body: body}, true, nil
}
