package runtime

import (
	"fmt"
	"strings"
)

func markCasePattern(stack []compoundFrame, line string, index int) {
	if len(stack) == 0 || stack[len(stack)-1].span.kind != compoundCase {
		return
	}
	top := &stack[len(stack)-1]
	if top.casePatternSet {
		return
	}
	pattern, ok := casePattern(line)
	if !ok || pattern == "" {
		return
	}
	top.casePattern = index
	top.casePatternSet = true
}

func requireCaseBoundary(stack []compoundFrame, line string) error {
	if len(stack) == 0 {
		return nil
	}
	top := stack[len(stack)-1]
	if top.span.kind != compoundCase || top.casePatternSet || caseCloserOrContinuation(line) {
		return nil
	}
	pattern, ok := casePattern(line)
	if !ok || pattern == "" {
		return fmt.Errorf("case: expected pattern)")
	}
	return nil
}

func caseCloserOrContinuation(line string) bool {
	return line == "esac" || strings.HasPrefix(line, "esac &&") || strings.HasPrefix(line, "esac ||") || strings.HasPrefix(line, "esac |")
}

func casePattern(line string) (string, bool) {
	pattern, ok := strings.CutSuffix(strings.TrimSpace(line), ")")
	if !ok {
		return pattern, false
	}
	// The open parenthesis POSIX 2.9.4.3 allows in front of a pattern -- `(a)` as
	// well as `a)`. It is what a `case` inside `$( )` is often written with, so
	// that a reader's paren matcher stays balanced, and scripts generated by
	// autoconf are full of it. Dropped here rather than at each use, because this
	// is the one place a pattern's text is settled: without it `(a)` became a
	// pattern beginning with a literal parenthesis, matched nothing, and the arm
	// silently never ran.
	return strings.TrimPrefix(pattern, "("), true
}

func closeCaseArm(stack []compoundFrame, index int) error {
	if err := requireTop(stack, compoundCase, ";;"); err != nil {
		return err
	}
	top := &stack[len(stack)-1]
	if !top.casePatternSet {
		return fmt.Errorf("case: expected pattern)")
	}
	top.span.caseArms = append(top.span.caseArms, caseArmSpan{
		patternIndex: top.casePattern,
		bodyStart:    top.casePattern + 1,
		bodyEnd:      index,
	})
	top.casePatternSet = false
	return nil
}
